# This workflow will check all the links in the Hugo site and report broken links.
# The link checker used is 'my-broken-link-checker': https://github.com/ruzickap/action-my-broken-link-checker

name: Hugo HTTP Link Check
on:
  # This event will only trigger a workflow run if the workflow file is on the default branch.
  # ucomment the following line if you want to run the workflow manually
  workflow_dispatch:
  # Run every day at 01h42 UTC (0:42 AM UTC aka 2:42 AM CEST with daylight saving time)
  schedule:
    - cron: '42 1 * * *'

jobs:
  build:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest
      
    # Steps to be executed as part of the job
    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step to set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # Always use the latest version of Hugo, in case of issue with the latest version, 
          # you can specify a specific version using '0.125.5'
          hugo-version: 'latest'
          # Set the extended option to true to install the extended version of Hugo, mandatory for Microcks website
          extended: true
      
      # Step to build the site
      - name: Build site
        run: hugo --minify
        # Capture output and error code
        continue-on-error: true
        id: build
      
      # Step to start Hugo server in the background
      - name: Start Hugo server
        run: hugo server --minify --port=8888 &
      
      # Check if build failed
      - name: Check build status
        run: |
          if [ ${{ steps.build.outcome }} != 'success' ]; then
            echo "::error::Hugo build failed, blocking commit..."
            exit 1
          fi

      # Check broken links in the Hugo site using my-broken-link-checker script
      - name: Check
        env:
          INPUT_URL: http://localhost:8888
          EXCLUDE: |
            linkedin.com
            localhost:8080
            twitter.com
            github.com
          #INPUT_PAGES_PATH: ./build/
          # --skip-tls-verification is mandatory parameter when using https and "PAGES_PATH"
          #INPUT_CMD_PARAMS: '--buffer-size=8192 --max-connections=10 --color=always --header="User-Agent:curl/7.54.0" --skip-tls-verification'
          #INPUT_CMD_PARAMS: '--verbose --buffer-size=8192 --max-connections=10 --color=always --header="User-Agent:curl/7.54.0"'
          INPUT_CMD_PARAMS: "--verbose --buffer-size=8192 --max-connections=10 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
          INPUT_DEBUG: "--debug=true"
          #run: wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v2/entrypoint.sh | bash
        run: muffet "${INPUT_CMD_PARAMS[@]}" "${INPUT_URL}" "${INPUT_DEBUG}" 
      # Check broken links in the Hugo site using my-broken-link-checker docker
      # - name: Check broken links
      #   uses: ruzickap/action-my-broken-link-checker@v2
      #   with:
      #     #url: http://127.0.0.1:8888/
      #     url: https://microcks.io/
      #     cmd_params: '--exclude=(linkedin.com) --buffer-size=8192 --max-connections=10 --color=always --header="User-Agent:curl/7.54.0"'
      #     debug: true

      # Stop the Hugo server at the end of the workflow as is running in the background
      - name: Stop Hugo server
        run: kill $(lsof -t -i:8888) || true
