# This workflow will check all the links in the Hugo site and report broken links.
# The link checker used is 'my-broken-link-checker': https://github.com/ruzickap/action-my-broken-link-checker

name: Hugo HTTP Link Check
on:
  # This event will only trigger a workflow run if the workflow file is on the default branch.
  # ucomment the following line if you want to run the workflow manually
  workflow_dispatch:
  # Run every day at 01h42 UTC (0:42 AM UTC aka 2:42 AM CEST with daylight saving time)
  schedule:
    - cron: '42 1 * * *'

jobs:
  build:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest
      
    # Steps to be executed as part of the job
    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step to set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # Always use the latest version of Hugo, in case of issue with the latest version, 
          # you can specify a specific version using '0.125.5'
          hugo-version: 'latest'
          # Set the extended option to true to install the extended version of Hugo, mandatory for Microcks website
          extended: true
      
      # Step to build the site
      - name: Build site
        run: hugo --minify
        # Capture output and error code
        continue-on-error: true
        id: build
      
      # Step to start Hugo server in the background
      - name: Start Hugo server
        run: hugo server --minify --port=8888 &
      
      # Check if build failed
      - name: Check build status
        run: |
          if [ ${{ steps.build.outcome }} != 'success' ]; then
            echo "::error::Hugo build failed, blocking commit..."
            exit 1
          fi

      # Step to install Muffet link checker tool in case it is not already installed
      - name: Check or install Muffet
        run: |
          if ! command -v muffet &> /dev/null; then
            echo "Muffet not found, installing..."
            if [ "${{ env.MUFFET_VERSION }}" = "latest" ]; then
              MUFFET_URL=$(wget -qO- https://api.github.com/repos/raviqqe/muffet/releases/latest | grep "browser_download_url.*muffet_linux_amd64.tar.gz" | cut -d \" -f 4)
            else
              MUFFET_URL="https://github.com/raviqqe/muffet/releases/download/v${{ env.MUFFET_VERSION }}/muffet_linux_amd64.tar.gz"
            fi
            wget -qO- "${MUFFET_URL}" | tar xzf - -C /usr/local/bin/ muffet
          else
            echo "Muffet is already installed."
          fi
        env:
            # Set the Muffet version to latest, you can specify a specific version using "0.1.0"
            MUFFET_VERSION: "latest"
            
      - name: Read file contents
        id: read-file
        run: |
          CONTENT=$(cat .lycheeignore)
          EXCLUDE=$(echo "$CONTENT" | grep -v '^#' | grep -oE '[^/]+.[^/]+/$' | sed '/^[[:space:]]*$/d')
          echo "EXCLUDE=$EXCLUDE" >> $GITHUB_ENV

      # Check broken links in the Hugo site using my-broken-link-checker script
      - name: Check
        env:
          URL: http://localhost:8888
          EXCLUDE: |
            fonts.gstatic.com
            use.fontawesome.com
            *.linkedin.com/*
            localhost:8080
            twitter.com
            github.com
          ARGS: '--buffer-size=8192 --color=always --header="User-Agent:curl/7.54.0" --timeout=42 --exclude=${EXCLUDE[@]}'
          #INPUT_CMD_PARAMS: '--buffer-size=8192 --max-connections=10 --color=always --header="User-Agent:curl/7.54.0" --skip-tls-verification'
          #INPUT_CMD_PARAMS: '--verbose --buffer-size=8192 --max-connections=10 --color=always --header="User-Agent:curl/7.54.0"'
          #INPUT_CMD_PARAMS: '--buffer-size=8192 --max-connections=10 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))'
          
          #run: wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v2/entrypoint.sh | bash
        #run: muffet "${INPUT_CMD_PARAMS[@]}" "${INPUT_URL}" "${INPUT_DEBUG}" 
        run: muffet ${ARGS} ${URL}

      # Check broken links in the Hugo site using my-broken-link-checker docker
      # - name: Check broken links
      #   uses: ruzickap/action-my-broken-link-checker@v2
      #   with:
      #     #url: http://127.0.0.1:8888/
      #     url: https://microcks.io/
      #     cmd_params: '--exclude=(linkedin.com) --buffer-size=8192 --max-connections=10 --color=always --header="User-Agent:curl/7.54.0"'
      #     debug: true

      # Stop the Hugo server at the end of the workflow as is running in the background
      - name: Stop Hugo server
        run: kill $(lsof -t -i:8888) || true
